name: Trigger Docs/Website

on:
  release:
    types: [published]

permissions: write-all

jobs:
  validate-tag-semver:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check_tag.outputs.valid }}
    steps:
      - name: Check if tag follows SemVer
        id: check_tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+|-beta\.[0-9]+)?$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: validate-tag-semver
    runs-on: ubuntu-latest
    if: needs.validate-tag-semver.outputs.valid == 'true'
    steps:
      - name: Run only once per release
        run: echo "Triggered by ${{ github.event_name }} with tag ${{ github.event.release.tag_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

  trigger-docs-and-web:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.result == 'success' && github.event.release.prerelease == false
    steps:
      - name: Trigger website build
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'rommapp',
              repo: 'marketing-site',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                version: '${{ github.event.release.tag_name }}'
              }
            });
            console.log(response);
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_PAT }}
