name: Trigger Docs/Website

on:
  release:
    types: [published]

permissions:
  actions: write

jobs:
  validate-tag-semver:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check_tag.outputs.valid }}
    steps:
      - name: Check if tag follows SemVer
        id: check_tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+|-beta\.[0-9]+)?$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: validate-tag-semver
    runs-on: ubuntu-latest
    if: needs.validate-tag-semver.outputs.valid == 'true'
    steps:
      - name: Run only once per release
        run: echo "Triggered by ${{ github.event_name }} with tag ${{ github.event.release.tag_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

  trigger-docs-and-web:
    permissions:
      actions: write
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.result == 'success' && github.event.release.prerelease == false
    steps:
      - name: Trigger docs build
        run: |
            curl -L -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${DOCS_PAT}" \
              "https://api.github.com/repos/rommapp/docs/actions/workflows/deploy.yml/dispatches" \
              -d '{"ref":"main", "inputs": {"version": "${{ github.event.release.tag_name }}"}}'
        env:
          DOCS_PAT: ${{ secrets.DOCS_PAT }}

      - name: Trigger website build
        run: |
            curl -L -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${DOCS_PAT}" \
              "https://api.github.com/repos/rommapp/marketing-site/actions/workflows/deploy.yml/dispatches" \
              -d '{"ref":"main", "inputs": {"version": "${{ github.event.release.tag_name }}"}}'
        env:
          DOCS_PAT: ${{ secrets.DOCS_PAT }}
