name: Trigger Docs/Website

on:
  release:
    types: [published]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.release.tag_name =~ '^\\d+\\.\\d+\\.\\d+(-alpha\\.\\d+|-beta\\.\\d+)?$'
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Run only once per release
        run: echo "Triggered by ${{ github.event_name }} with tag ${{ github.event.release.tag_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

  trigger-docs-and-web:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - name: Trigger docs build
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'romapp',
              repo: 'docs',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                version: '${{ github.event.release.tag_name }}'
              }
            });
            console.log(response);

      - name: Trigger website build
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'romapp',
              repo: 'marketing-site',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                version: '${{ github.event.release.tag_name }}'
              }
            });
            console.log(response);
